method: onet
data:
  dataset: MN40
  input_type: pointcloud
  path: data/MN40
  pointcloud_n: 300
  pointcloud_noise: 0.005
  points_subsample: 2048
  pointcloud_order: true
  pointcloud_rotation: true
  pointcloud_rot90: true
  voxels_file: null
model:
  encoder_latent: null
  decoder: cbatchnorm
  encoder: pointnet_resnet
  encoder_kwargs:
    hidden_dim: 512
  c_dim: 512
  z_dim: 0
training:
  out_dir:  out/pointcloud/onet_mn40
  batch_size: 64
  print_every: 50
  visualize_every: -1
  checkpoint_every: -1
  validate_every: 1000
  backup_every: 1000
  model_selection_metric: iou
  model_selection_mode: maximize
  lr_scheduler: false
test:
  model_file: 'pretrain/onet.pth'
  threshold: 0.2
  eval_mesh: false
  eval_pointcloud: true
generation:
  resolution_0: 32
  upsampling_steps: 2
  batch_size: 100000
  refine: false
  n_x: 128
  n_z: 1
