method: conv_onet
data:
  dataset: MN40
  input_type: pointcloud
  classes: null
  path: data/MN40
  pointcloud_n: 600 # changed from 3000
  pointcloud_noise: 0.005
  points_subsample: 2048
  pointcloud_order: true
  pointcloud_rotation: true
  pointcloud_rot90: true
  pointcloud_rot90_val: false
  points_file: points.npz
  points_iou_file: points.npz
  voxels_file: null
model:
  encoder: pointnet_local_pool
  encoder_kwargs:
    hidden_dim: 32
    plane_type: ['xz', 'xy', 'yz']
    plane_resolution: 64
    unet: True
    unet_kwargs:
      depth: 4
      merge_mode: concat
      start_filts: 32
  decoder: simple_local
  decoder_kwargs:
    sample_mode: bilinear # bilinear / nearest
    hidden_size: 32
  c_dim: 32
training:
  out_dir: out/pointcloud/convonet_3plane_mn40
  batch_size: 32
  model_selection_metric: iou
  model_selection_mode: maximize
  print_every: 1000
  visualize_every: 10000
  validate_every: 10000
  checkpoint_every: 2000
  backup_every: 10000
  n_workers: 8
  n_workers_val: 4
test:
  threshold: 0.2
  eval_mesh: true
  eval_pointcloud: false
  model_file: 'pretrain/convonet.pth'
generation:
  vis_n_outputs: 2
  refine: false
  n_x: 128
  n_z: 1
